tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform.sh
      source ./bin/create_tfrc_credentials.sh
      source ./bin/set_tf_alias.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/set_tf_alias.sh
      source ./bin/install_aws_cli.sh
  - name: http-server
    before: |
      npm install --global http-server  
    command:
      http-server

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - mhutchie.git-graph
