tasks:
  - name: terraform
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform.sh
      source ./bin/create_tfrc_credentials.sh
      source ./bin/set_tf_alias.sh
      source ./bin/build_provider.sh
      cp terraform.tfvars.example zzzvariables.auto.tfvars
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/set_tf_alias.sh
      source ./bin/install_aws_cli.sh
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server  
    command:
      http-server

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - mhutchie.git-graph
